### ISSUE TITLE
After opening a file working with VsVim isn't possible

### ISSUE THREAD

**Issue by MartinL0815** [parnic/VSQuickOpenFile#8]
If I open a file with this extension and want directly to start typing using the VsVim extension, then since some time I need first to click with the mouse pointer into the window, the text editor area.
After this click I can start typing using keys to move the caret, start searches, editing the text.
There has been a change in behavior, since this wasn't a problem before.

**Comment by baseanalog** [comment]
I have a similar issue - if you open a file via this extension, then hit 'ctrl-f', it does not focus on the find text field - it's still in the document, so if you then start typing it'll be modifying instead of searching. Was driving me crazy until I figured out it was just after using this extension. I downgraded to 14.0 as suggested and that doesn't have this problem.

**Comment by parnic** [comment]
Thank you for the feedback. I'll revert the particular change that probably caused this.

**Comment by parnic** [comment]
v1.15.2 has been published to fix this.

**Comment by baseanalog** [comment]
Thanks for the speedy response! I've had no problems otherwise and use this constantly, It's so much faster than alternatives I've tried. Wish I could help with #7. Good luck!
